---
# tasks file for roles/docker
- name: Install device-mapper-persistent-data and lvm2
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - device-mapper-persistent-data
    - lvm2
   
- name: Add Docker repository
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Install Docker
  yum:
    name: docker-ce
    state: present

- name: Install python3
  yum:
    name: python3
    state: present

- name: Install docker with python3
  pip:
    name: docker
    executable: pip3
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Make sure Docker is started
  service: name=docker state=started
  tags: docker