---
# tasks file for roles/proxy
- name: Lunch the proxy container
  docker_container:
    name: proxy
    image: okzie/httpserv:latest
    ports:
      - "80:80"
    state: started
    restart_policy: always
    networks:
      - name: my_network
    pull: true