name: CI devops 2023 - Deploy app
on:
  workflow_run:
    workflows: ["CI devops 2023 - Build and Push Docker Image"]
    types:
      - completed
    branches:
      - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: github.event.workflow_run.conclusion == 'success'
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2
    
        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'
    
        - name: Install Ansible
          run: pip install ansible
    
        - name: Run Ansible playbook
          run: |
            mkdir -p ~/.ssh
            ssh-keyscan -H florian.le-coustumer.takima.cloud >> ~/.ssh/known_hosts
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/devops_aws
            chmod 400 ~/.ssh/devops_aws
            ansible-playbook -i ./TP3/ansible/inventories/setup.yml ./TP3/ansible/playbook.yml

